### ISSUE TITLE
Suggestion: get rid of file saving functionality

### ISSUE THREAD

**Issue by kot-lex** [picuscreative/testcafe-reporter-html#1]
Hello there!

Is there any significant why do you use your own report file saving mechanism instead of the one that comes with testcafe? 

It seems like I could use command
testcafe --reporter html:public/index.html [documentation](http://devexpress.github.io/testcafe/documentation/using-testcafe/command-line-interface.html#-r-namefile---reporter-namefile)
instead of creating tcr-html.config.js file. 

Am I missing something?

**Comment by davidcunha** [comment]
Hello @kot-lex and thank you for helping us on building this reporter!

The initial idea for this file was to have a config where we could add client's name, client's logo, and any sort of project-specific configuration. However atm it's not very useful as it only allows for options that can be easily added by that command.

Feel free to submit a PR 😄

**Comment by kot-lex** [comment]
We also have a need for project-specific customization. I guess it is better to provide a way to replace the whole html template by the one provided by user.
Though, I'm not sure what is the best way of implementing this

**Comment by davidcunha** [comment]
@kot-lex Yeah I like your idea. Initially we wanted to keep it simple and use the actual template, but with just our company's logo, client's logo and client's name. From there we can then grow to several themes and a deeper customization.

I'll let you know if we gonna tackle this in the near future.

**Comment by timnederhoff** [comment]
Hi, I felt free to submit a PR :smile: #13 
Also, I agree with you guys having a default html report and the option to use a custom html template from your project. A Nunjucks or Handlebars template or the like. When I have some spare time, I can work some ideas out.

**Comment by timnederhoff** [comment]
@davidcunha do you agree with the PR?

**Comment by davidcunha** [comment]
@timnederhoff Yes. The thing is that we wanted to use the config for more than the output file. For example, logo, color scheme, etc. Anyway as I wasn't able to code those features, the config file as it is, is useless.
