### ISSUE TITLE
HTML tags are not esacped in error details

### ISSUE THREAD

**Issue by janrozycki** [picuscreative/testcafe-reporter-html#14]
I'm using TestCafe with TypeScrpt and I noticed that in some cases errors from TestCafe are cointaining type definitions which are treated by browser as opening HTML tag. Fo example:
`let myArray: Array<object> = [];`
This also affects a stacktrace present in an error, which sometimes contains lines similar to the one below:
`at MyClass.<anonymous> (C:\Path\to\file.ts)`
This causes that errors displayed in the browser are not 100% correct and entire HTML structure is jumbled (as some browsers are automatically closing unclosed tags at the end of a DOM structure)

**Comment by timnederhoff** [comment]
Did a PR #15 that include escaping the error code for html (+ curly braces { })

**Comment by davidcunha** [comment]
Awesome, thanks @timnederhoff ✌️
