### ISSUE TITLE
Report is written to file index.html by default

### ISSUE THREAD

**Issue by janrozycki** [picuscreative/testcafe-reporter-html#16]
Readme states that report is returned by default to stdout, but in reality it is also saved to a file named index.html on a root level. It happens when I'm running TestCafe through programming interface (https://devexpress.github.io/testcafe/documentation/using-testcafe/programming-interface/runner.html#reporter).
Additionally when I specify outStream argument to write to file (saved in specific repository), it's being saved there properly but reporter still saves the same result to index.html file in root folder.

**Comment by davidcunha** [comment]
@janrozycki Thanks for the report. I'll investigate that.

**Comment by davidcunha** [comment]
@janrozycki I released a new version https://github.com/picuscreative/testcafe-reporter-html/releases/tag/v1.4.4 because of a change in the README and everything seems to be ok now. Let me know if it works on your side 👍

**Comment by timnederhoff** [comment]
Works on my side :+1: thanks for fixing it!

**Comment by janrozycki** [comment]
Works on my side as well.
Many thanks for the fix! 👍
