### ISSUE TITLE
In a README.md have not a screenshot

### ISSUE THREAD

**Issue by AnotherAnkor** [picuscreative/testcafe-reporter-html#17]
In a title page of the project I can't find a screenshot of resulted html file.
I think you should add it to show why I need install your plugin.

**Comment by davidcunha** [comment]
@AnotherAnkor Thanks for the comment. I'll add it!

**Comment by davidcunha** [comment]
@AnotherAnkor I added a gif in the README: https://github.com/picuscreative/testcafe-reporter-html/pull/18
