### ISSUE TITLE
Can Screenshots be embedded in this report for failed tests?

### ISSUE THREAD

**Issue by skullz03** [picuscreative/testcafe-reporter-html#22]
Hi, 

I have the following line in my package.json
"test-with-html-reports": "testcafe chrome TestCafe-Demo/tests/ --reporter html:TestCafe-Demo/reports/html -e --proxy https.mycom.test.com:7000 -S -s artifacts/screenshots",

As you can see, I am making screenshots in the folder "artifacts" when the test fails. Could this be somehow shown in the report. Does this reporter plugin support that ?

**Comment by chopra1203** [comment]
Hello, Are there any updates on this topic ? I am also looking for similar feature to include screen shots in HTML test reports.

**Comment by martinkasa** [comment]
@skullz03 @chopra1203 
I have installed this library today and I can see screenshots of failed test in a report. HTML report and screenshot path are set on the same folder in my case. Maybe it works just in this setup.

**Comment by timnederhoff** [comment]
This is and old issue. screenshots are now embedded in the HTML.

**Comment by RanjaniThoppe19** [comment]
Can you pls throw some light on this ? I am struggling to embed my screenshot in the report.

**Comment by timnederhoff** [comment]
OK, what command do you use to start your tests? what version do you use? Screenshots will be embedded automatically if you set the screenshot arguments correctly

**Comment by RanjaniThoppe19** [comment]
I am a newbie , i use npm run testvideo (name of the testscript). testcafe version 1.8.5

**Comment by RanjaniThoppe19** [comment]
Can you pls share how to set the screenshot arguments ?

**Comment by timnederhoff** [comment]
ok, If you have questions about running testcafe then please refer to the [Testcafe docs](https://devexpress.github.io/testcafe/documentation/reference/)

**Comment by RanjaniThoppe19** [comment]
"test": "testcafe chrome:headless testcafe/tests --env-Test --reporter html:TestResults.html -s takeOnFails=true -p '${DATE}/${DATE}_${TIME}_${FIXTURE}_${TEST}.png'",
    "testvideo": "testcafe chrome:headless testcafe/tests --video videos --video-options failedOnly=true,pathPattern='${DATE}/${DATE}_${TIME}_${FIXTURE}_${TEST}.mp4'"


these are in my package.json

**Comment by timnederhoff** [comment]
this part can help you: https://devexpress.github.io/testcafe/documentation/reference/command-line-interface.html#-s-path---screenshots-path

**Comment by RanjaniThoppe19** [comment]
Hurray ! I got it now, thank you so much !
